-- AlterTable
ALTER TABLE "CashLedger" ADD COLUMN     "actualCash" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "expectedCash" DOUBLE PRECISION NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "ShiftAudit" ADD COLUMN     "difference" DOUBLE PRECISION NOT NULL DEFAULT 0;
